# Generated by Django 5.0.8 on 2025-06-30 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_disasters', to=settings.AUTH_USER_MODEL),
        ),
    ]
