# Generated by Django 5.0.8 on 2025-06-30 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_disaster_flagged_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userhelp',
            name='claimed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'Organization'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
