# Generated by Django 5.2.16 on 2026-07-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(db_index=True, max_length=100)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("heat", "Heat warning"),
                            ("cold", "Cold warning"),
                            ("rain", "Rain warning"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[("user", "User"), ("system", "System")],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                ("rain_mm", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
